# Generated by Django 4.0.5 on 2022-07-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App19', '0002_estudiante_email_profesor_email_profesor_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregable',
            name='fecha_entrega',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
